import subprocess
import os

def add_loc(key, en, ja, zh):
    cmd = ["python", "add_localization.py", key, en, ja, zh]
    subprocess.run(cmd, check=True)

# Monster Names mapping for flavor text clarity
monsters = {
    "A": "Ant", "B": "Bat", "C": "Cobra", "D": "Dragon", "E": "Ent",
    "F": "Fly", "G": "Goblin", "H": "Harpy", "I": "Imp", "J": "Jelly",
    "K": "Kobold", "L": "Lizard", "M": "Mummy", "N": "Naga", "O": "Orc",
    "P": "Pixie", "Q": "Coeurl", "R": "Rat", "S": "Slime", "T": "Troll",
    "U": "Undead", "V": "Vampire", "W": "Wolf", "X": "Xalthis", "Y": "Yeti", "Z": "Zombie"
}

# Gravity Skill Flavor Texts
gravity_data = {
    "A": ("The ant's shell cracked under the sudden gravitational pressure. It was pinned to the ground, unable to move a single leg. The weight of the world proved too much for the small insect.",
          "アリの甲殻が突如とした重圧に悲鳴を上げた。地面に縫い付けられ、一本の脚すら動かせない。小さな虫にとって、世界の重みはあまりに過酷だった。",
          "蚂蚁的甲壳在突如其来的重压下发出了哀鸣。它被钉在地上，连一条腿也动弹不得。对于这只小昆虫来说，世界的重量实在太过沉重。"),
    "B": ("The bat's delicate wings were dragged down by an invisible force. It crashed into the stone floor with a dull, heavy thud. Gravity claimed the master of the air as its own.",
          "コウモリの繊細な翼が不可視の力によって引きずり下ろされた。鈍い衝撃音と共に、魔物は石の床へと叩きつけられた。重力が空の支配者を地に縛り付けた。",
          "蝙蝠纤细的双翼被一股无形的力量强行拽下。伴随着沉闷的撞击声，魔物重重地摔在了石地板上。重力将这片天空的支配者束缚在了大地上。"),
    "C": ("The cobra's long body was flattened against the earth by intense gravity. Its venomous fangs could only bite the cold, hard floor. The serpent's elegant coil was crushed in an instant.",
          "コブラの長い体躯が、強烈な重力によって地面に押し潰された。猛毒の牙は冷たい床を噛むことしかできない。優雅な鎌首も、一瞬にして重圧の前に屈した。",
          "眼镜蛇长长的躯体在强烈的重力作用下被压扁在地面上。那对剧毒的獠牙只能咬住冰冷而坚硬的地板。它那优雅的盘踞姿态在瞬间就被重压摧毁了。"),
    "D": ("Even the mighty dragon found its massive weight multiplied ten-fold. Its wings collapsed under the internal pressure and it hit the ground with a tremor. The sky-king fell before the power of the earth itself.",
          "強力なドラゴンの巨躯でさえ、自身の重みが十倍になったかのように沈み込んだ。内部からの重圧に翼は折れ、大地を揺らして墜落した。空の王は、惑星の力の前に膝を突いた。",
          "即使是强大的巨龙，其庞大的身躯也似乎承受了十倍于自身的重量。双翼在内部重压下折断，震撼着大地坠落了。天空之王在行星的力量面前屈膝倒下。"),
    "E": ("The ancient spirit's wooden trunk groaned and snapped under the weight. Its roots were crushed into the dirt, ending its sentinel duty. The forest became silent as the Ent fell into the earth.",
          "古の精霊の硬い幹が、重圧に耐えかねて轟音と共にへし折れた。根は深く土に沈み込み、守護者としての役目を終えた。エントが地に還る時、森に静寂が訪れた。",
          "古老之灵坚硬的躯干无法承受重压，伴随着轰鸣声折断了。根部深深陷入土中，结束了它作为守护者的职责。当树精回归大地之时，森林陷入了沉寂。"),
    "F": ("The annoying fly was swatted out of the air by a localized gravity field. It fell like a lead pellet, ending its buzzing forever. The tiny pest was crushed by a force it couldn't understand.",
          "目障りなハエが、局所的な重力場によって空から叩き落とされた。鉛の粒のように落下し、その不快な羽音は永遠に絶たれた。小さな害虫は、理解不能な力に圧し潰された。",
          "那只碍眼的苍蝇被局部重力场从空中击落。它像铅弹一样坠下，那令人不快的嗡鸣声永远消失了。这只微小的害虫被一种它无法理解的力量压扁了。"),
    "G": ("The goblin's cowardly knees buckled as gravity doubled in an instant. It tried to crawl away, but the dirt claimed its miserable form. The weight of its crimes seemed to manifest literally.",
          "ゴブリンの卑屈な膝が、一瞬で倍増した重力によってへし折れた。這いつくばって逃げようとするが、地面が奴の惨めな姿を捉えて離さない。犯した罪の重さが具現化したかのようだった。",
          "哥布林卑下的膝盖在瞬间倍增的重力作用下折断了。它试图爬行逃跑，但地面死死地抓住了它那悲惨的身影。这仿佛是它所犯下的罪孽之重具现化了一般。"),
    "H": ("Extreme gravity turned the harpy's light frame into a heavy burden. She shrieked as her hollow bones began to crack under the strain. The master of the heights was silenced by the gravity's pull.",
          "極限の重力が、ハーピーの軽い身体を重い重荷へと変えた。負荷に耐えかねて中空の骨が軋み、彼女は絶叫と共に地に堕ちた。高空の支配者は、引力の前に沈黙した。",
          "极限重力将哈皮轻盈的身体变成了沉重的负担。由于无法承受负荷，她那中空的骨头咔哒作响，在一声绝叫中坠落在地。高空的支配者在引力面前陷入了沉默。"),
    "I": ("The arrogant imp tried to resist, but its small body was flattened against the stone. Its magical whispers were cut short by the crushing weight. The devilish prankster met a heavy end.",
          "小賢しいインプは抵抗を試みたが、その身体は冷たい石畳に押し潰された。悪魔的なささやきは、圧殺される重みの前に途絶えた。悪戯好きな小悪魔に、重苦しい最期が訪れた。",
          "狡猾的小恶魔试图反抗，但它的身体被压扁在冰冷的石地板上。那恶魔般的低语在令人窒息的重压之下一蹶不振。爱开玩笑的小恶魔迎来了沉重的末日。"),
    "J": ("The jelly's liquid form could no longer hold its shape under the pressure. It spread out thin across the floor until its core was exposed. The monster turned into a mere colorful stain.",
          "ジェリーの流動的な身体は、重圧の下で形を保つことができなかった。核が露出するまで薄く引き延ばされ、やがて液体へと還った。怪物は床に広がる、単なる色鮮やかなシミと化した。",
          "果冻怪那流动的身体在重压之下无法维持形状。它被压得薄薄地铺开在地上，直到核心暴露。怪物变成了地板上一抹单纯而鲜艳的污渍。"),
    "K": ("The kobold let out a high-pitched yelp as it was crushed into the dirt. Its frantic scratching did nothing against the invisible weight. The canine warrior was defeated by the earth's pull.",
          "コボルドは甲高い悲鳴を上げながら、土の中に押し込められた。必死の抵抗も不可視の重みの前には無意味だった。犬面の戦士は、大地の引力に完敗した。",
          "狗头人发出一声尖厉的悲鸣，随后被压入土中。即使拼命挣扎，在无形的重压面前也毫无意义。这名犬面战士在大地的引力面前一败涂地。"),
    "L": ("The desert lizard's low profile didn't save it from the gravitational surge. Its scales cracked as the pressure drove it into the hot sand. The predator became a flat, lifeless carving.",
          "砂漠の捕食者であるリザードも、重力の奔流からは逃れられなかった。圧力が身体を熱い砂に埋め込み、その鱗は無惨に砕けた。冷血な獣は、命なき平坦な彫刻へと成り果てた。",
          "即使是沙漠中的掠食者蜥蜴，也没能逃过重力的奔流。重压将它的身体埋入热沙之中，鳞片惨遭破碎。这只冷血的野兽化为了毫无生气的扁平雕刻。"),
    "M": ("The mummy's dry bones turned to dust as the gravity increased. Its ancient bandages offered no protection against the physical pressure. The eternity of its curse ended under the heavy weight.",
          "重力が増すにつれ、マミーの乾いた骨は塵へと還っていった。古の包帯も、物理的な重圧の前には何の守りにもならなかった。数千年の呪縛は、重苦しい終焉を迎えた。",
          "随着重力增加，木乃伊枯干的骨头化为了尘土。古老的绷带在物理重压面前起不到任何保护作用。几千年的束缚迎来了沉重的终结。"),
    "N": ("The naga's agile escape failed as her body became too heavy to lift. She could only hiss in surprise as the gravity pinned her down. Her beautiful serpent form was crushed into the earth.",
          "ナーガの敏捷な回避も、身体が持ち上がらぬほど重くなっては意味を成さない。不意の重圧に驚愕の声を上げ、彼女は地に縫い付けられた。美しき蛇身は、大地に屈した。",
          "由于身体变得沉重到无法抬起，纳迦那敏捷的躲避也失去了意义。她因突如其来的重压发出惊愕之声，被钉在地上。美丽的蛇身向大地屈服了。"),
    "O": ("The mighty orc's shield felt like a mountain in its arms. It tried to stand, but its powerful legs snapped under the weight. The brute was brought low by a force it couldn't fight.",
          "強大なオークの盾が、腕の中で山のような重荷と化した。立ち上がろうとするが、強靭な脚が重圧に耐えかねて折れた。蛮勇の怪物は、抗えぬ力の前に屈辱の伏臥を強いられた。",
          "强大兽人的盾牌在双臂中变成了山岳般的沉重负担。它试图站起，但强健的双腿在重压之下折断了。蛮勇的怪物在无法抗衡的力量面前被迫屈辱地趴下。"),
    "P": ("The pixie's magical lights winked out as the air itself grew heavy. She fell from the sky like a stone, ending her tricks forever. The light of the forest was snuffed out by the gravity.",
          "空気が重苦しく澱み、ピクシーの魔法の光が一つ、また一つと消えた。彼女は石のように空から墜ち、悪戯の時間は永遠に終わった。森の灯火は、重力によってかき消された。",
          "空气变得沉重压抑，小仙女的魔法之光一个接一个地熄灭了。她像石头一样从空坠落，恶作剧的时间永远结束了。森林的灯火被重力抹杀了。"),
    "Q": ("The coeurl's electric fur sparked wildly as gravity distorted the air. Its sense of balance failed and it collapsed into a heap. The high-speed beast was slowed down to a halt by the weight.",
          "重力が空気を歪め、クアールの帯電した毛皮が激しく火花を散らした。平衡感覚を失った獣は、なす術なくその場に崩れ落ちた。高速の捕食者は、重みの前に静止を余儀なくされた。",
          "重力扭曲了空气，夸尔带电的毛皮剧烈地溅出火花。失去平衡感的野兽束手无策地当场倒下。这只高速掠食者在重压面前被迫停止了行动。"),
    "R": ("The swarm of rats was flattened into a singular carpet of fur. Their squeaks were cut short as the gravity crushed their small hearts. The pack's numbers meant nothing against the crushing weight.",
          "ラットの群れは、一瞬にして毛皮の絨毯のように地面へ押し潰された。小さな心臓が重圧に屈し、甲高い鳴き声は絶たれた。数の暴力も、空間を支配する重みの前には無力だった。",
          "鼠群瞬间被压扁在地上，犹如一张皮毛地毯。微小的心脏在重压下屈服，尖锐的鸣叫声戛然而止。在支配空间的重压面前，数量的暴力也显得毫无意义。"),
    "S": ("The slime's nucleus was shattered as the gravity intensified. It couldn't maintain its surface tension and dissolved into a puddle. The gelatinous monster lost its form and its life.",
          "重力が増大し、スライムの中心にある核が無残に砕け散った。表面張力を維持できなくなり、怪物はただの不気味な液だまりへと化した。ゼリー状の肉体は形と命を同時に失った。",
          "重力增大，史莱姆中心的核心惨遭破碎。它再也无法维持表面张力，怪物化为了一滩诡异的积液。胶状的肉体同时失去了形状与生命。"),
    "T": ("The troll's massive club became too heavy for it to even hold. It collapsed under its own weight despite its legendary strength. Gravity ended the brute's rampage where steel couldn't.",
          "トロールの巨大な棍棒は、持ち上げることすら不可能な重荷となった。怪力自慢の魔物も自重に耐えられず崩れ落ち、膝を突いた。鋼の刃が届かぬ巨躯を、重力が静かに沈めた。",
          "巨魔巨大的木棒变成了甚至无法举起的重担。自诩怪力的魔物也无法承受自重而瘫倒跪下。重力静静地沉降了连钢刃都无法触及的庞大躯体。"),
    "U": ("Even the incorporeal undead felt the heavy pull of the void. Their spectral form wavered and faded as gravity distorted the spirit realm. The dead were finally returned to the earth's embrace.",
          "実体のないアンデッドでさえ、虚空からの重い引力に抗えなかった。重力が霊界を歪め、亡霊の姿は揺らぎ、やがて霧散していった。死者はようやく、大地の抱擁の中へと還っていった。",
          "即使是没有实体的亡灵，也无法抗拒虚空传来的沉重引力。重力扭曲了灵界，亡灵的身影摇曳着，最终烟消云散。死者终于回到了大地的怀抱。"),
    "V": ("The vampire's noble grace vanished as his body became a leaden anchor. He tried to mist away, but gravity held his essence to the floor. The prince of darkness fell before the planet's power.",
          "ヴァンパイアの優雅な身のこなしは消え、その身体は鉛の重しと化した。霧となって逃れようとするが、引力がその本質を床に留めた。闇の貴族は、惑星の力の前に無様に伏した。",
          "吸血鬼优雅的身姿消失了，他的身体变成了沉重的铅块。他试图化作雾气逃走，但引力将其本质留在了地板上。黑暗贵族在行星的力量面前狼狈地趴下了。"),
    "W": ("The wolf pack's coordination was broken as the leader was pinned down. They whined in fear as gravity crushed their agile limbs. The hunters became the helpless prey under the weight.",
          "リーダーが地に伏し、ウルフの群れの統制は瞬時に崩壊した。敏捷な四肢を重力に砕かれ、獣たちは恐怖の悲鳴を上げた。誇り高き狩人は、重みの下で無力な獲物へと成り果てた。",
          "随着首领倒地，狼群的统制瞬间崩溃。敏捷的四肢被重力压碎，兽群发出了恐惧的悲鸣。高傲的狩猎者在重压之下沦为了无力的猎物。"),
    "X": ("Xalthis tried to scuttle away on its many legs, but they snapped like twigs. Its venomous body was flattened against the cold dungeon floor. The multi-legged terror was silenced by gravity's cold hand.",
          "ザルティスは多足で逃げようとしたが、それらは小枝のように容易く折れた。毒を持つ身体は冷たい床へと叩きつけられ、逃走は絶たれた。多足の恐怖は、重力の冷徹な手によって沈黙した。",
          "扎尔提斯试图用多肢逃跑，但那些肢体像小枝一样轻易折断了。带毒的身体被重重摔在冰冷的地板上，逃跑被阻断了。多肢的恐怖在重力冷彻的手中陷入了沈默。"),
    "Y": ("The yeti's mountain-like presence was brought down to a crawl. The cold giant's heart stopped under the unnatural gravitational shear. The king of the peaks fell to the pull of the depths.",
          "山のような威容を誇るイエティも、這いつくばることを強いられた。不自然な重圧によって雪山の巨人の鼓動は止まり、その巨躯は沈黙した。山嶺の王は、底知れぬ引力の前に敗れ去った。",
          "拥有山岳般威严的雪人也被迫趴下。由于不自然的重压，雪山巨人的心跳停止，庞大的身躯陷入了沈默。山岭之王在深不见底的引力面前败北了。"),
    "Z": ("The zombie's rotting flesh sloughed off as it was ground into the dirt. Its unfeeling existence met a final, crushing end under the weight. The living dead were finally given a permanent grave.",
          "ゾンビの腐敗した肉体が、地面に擦り潰されながら剥がれ落ちていった。痛みを知らぬ身体も重圧の前には無力で、その活動を永久に停止した。動く死体はついに、逃れられぬ墓穴へと沈んだ。",
          "僵尸腐烂的肉体在地面摩擦挤压中剥落。即使是不知疼痛的身体在重压面前也无能为力，永久停止了活动。会动的尸体终于沉入了无法逃脱的墓穴。")
}

# Win/Loss status mapping for logic
win_status = {
    "Gravity": ["A", "B", "C", "D", "E", "F", "G", "H", "K", "L", "M", "P"],
    "Illusion": ["A", "B", "C", "D", "F", "I", "J", "L", "M", "N", "Q", "U"],
    "Napalm": ["A", "B", "E", "G", "H", "I", "J", "K", "O", "R", "S", "V"]
}

# Helper to generate localized flavor texts
def process_skill(skill_name, data_map, wins):
    print(f"Adding localizations for {skill_name}...")
    for eid, (en, ja, zh) in data_map.items():
        is_win = eid in wins
        suffix = "WIN" if is_win else "LOSS"
        key = f"MSG_C_{skill_name.upper()}_{eid}_{suffix}"
        add_loc(key, en, ja, zh)

# Illusion Skill Flavor Texts (Wins and Losses combined list)
illusion_data = {
    "A": ("The ant chased a phantom scent into a bottomless pit. It fell forever in a dream while its true body stood still. Reality vanished behind a veil of beautiful, deceptive images.",
          "アリは幻のフェロモンを追い、底なしの落とし穴へと足を踏み入れた。意識が夢を彷徨う間に、現実に残された身体は静かに朽ちていった。真実は、美しき欺瞞のベールの向こう側に消えた。",
          "蚂蚁追逐着幻觉中的费洛蒙，踏入了无底深渊。当意识在梦境中徘徊时，留在现实中的身体静静地腐朽了。真实消失在了美丽的欺瞒之纱的另一侧。"),
    "B": ("The bat's sonar was confused by echoes of non-existent walls. It crashed in panic while trying to navigate a world that wasn't there. The master of darkness was defeated by a false light.",
          "コウモリの超音波が、存在しない壁の残響に惑わされた。実体のない世界を進もうとした魔物は、パニックに陥り激突を繰り返した。闇の支配者は、偽りの光にその誇りを砕かれた。",
          "蝙蝠的超音波被不存在的墙壁残响所迷惑。试图进入虚幻世界的魔物陷入恐慌，反复撞击。黑暗的支配者在那虚假的光芒面前折损了自尊。"),
    "C": ("The cobra struck at a shimmering mirage of a giant bird. It exhausted its venom on shadows before the true blade bit its neck. The serpent died chasing a lie of its own fear.",
          "コブラは巨大な鳥の幻影に向かって、猛然と牙を剥いた。実体のない影に毒を浴びせ続け、背後の真実には気づくことさえなかった。毒蛇は、自らの恐怖が紡いだ嘘を追って絶命した。",
          "眼镜蛇朝着巨鸟的幻影猛然亮起獠牙。它不断向虚无的影子喷洒毒液，甚至没有察觉身后的真相。毒蛇追逐着由自身恐惧编织的谎言而毙命。"),
    "D": ("The dragon fought a spectral army of knights in the clouds. It wasted its fire on ghosts until it fell from sheer exhaustion. The legend was broken by a story it couldn't win against.",
          "ドラゴンは雲の中で、亡霊の騎士団と果てなき戦いを繰り広げた。実体のない幻にブレスを吐き続け、やがて極限の疲労と共に墜落した。伝説は、勝てるはずのない空想の物語に敗れた。",
          "巨龙在云层中与亡灵骑士团展开了无止境的战斗。它不断向虚幻的假象喷出吐息，最终伴随着极度的疲劳坠落。传说败在了一个注定无法获胜的幻想故事手中。"),
    "E": ("The forest guardian attacked a forest fire that didn't exist. It tore its own bark apart trying to save phantoms from the flames. Reflection of its own protectiveness led to its ruin.",
          "森の守護者は、存在しない山火事から仲間を救おうと狂奔した。幻の炎から森を守るため自身を傷つけ、守護の情熱は自滅へと変わった。慈しみゆえの過ちが、エントの終焉を招いた。",
          "森林守护者为了从不存在的山火中救出同伴而狂奔。为了保护森林免受幻觉之火的侵害而伤害了自己，守护的热情变成了自取毁灭。因慈悲而犯下的错误招致了树精的终焉。"),
    "F": ("The fly hit an invisible barrier created by a complex illusion. It became trapped in a kaleidoscope of light until it stopped moving. The tiny insect was lost in a world of infinite colors.",
          "ハエは万華鏡のような光の迷宮に迷い込み、出口を求めて虚しく羽ばたいた。無数に重なる色の渦に視覚を奪われ、やがて生命の鼓動は停止した。小さな虫は、極彩色の絶望の中に沈んだ。",
          "苍蝇迷失在万花筒般的光之迷宫中，为了寻找出口而徒劳地扇动着翅膀。视线被无数重叠的色彩漩涡夺走，不久生命的心跳便停止了。微小的昆虫沉没在极彩色的绝望之中。"),
    "G": ("The goblin saw a phantom pile of gold and let its guard down. It was stabbed by the very air as the illusion faded into blood. Its greed made it the perfect target for a fake dream.",
          "ゴブリンは目の前の金貨の山に目を奪われ、その卑屈な警戒心を解いた。夢中で幻を掴もうとしたその瞬間、冷たい刃が奴の胸を貫いた。強欲さは、偽りの夢への片道切符となった。",
          "哥布林被眼前的金币堆夺走了视线，放下了它那猥琐的戒心。在它忘我地想要抓住幻觉的瞬间，冰冷的利刃贯穿了它的胸膛。贪婪成了它通往虚假梦境的单程票。"),
    "H": ("A harpy saw its lost sister in the clouds and stopped its attack. It reached out only to touch a cold, sharp reality. The queen of the sky died with a heart filled with false hope.",
          "ハーピーは雲間に失ったはずの同胞の姿を見、逆転の牙を収めた。再会の喜びに手を伸ばした瞬間、彼女を貫いたのは冷酷な真実だった。空の女王は、偽りの希望を抱いたまま奈落へ堕ちた。",
          "哈皮在云间看到了本该失去的同伴身影，收回了反击的獠牙。在为了重逢的喜悦而伸出手的瞬间，刺穿她的却是冷酷的真相。天空之女王怀揣着虚假的希望坠入了深渊。"),
    "I": ("The imp's own pranks were reflected back at it ten-fold. It became terrified of its own shadow, thinking it was a high demon. The prankster was driven mad by its own medicine.",
          "インプの得意とした悪戯が、十倍の恐怖となって自身に跳ね返った。自らの影を上位の悪魔と誤認し、小悪魔は狂乱の果てに自滅した。人を欺く者は、最後には自らの幻想に食い尽くされた。",
          "小恶魔擅长的恶作剧化作十倍的恐惧反弹到了自己身上。将自己的影子误认为上位恶魔，小恶魔在狂乱的最后自取灭亡。欺骗他人者，最终会被自己的幻想吞噬。"),
    "J": ("The jelly's simple mind was overloaded by a barrage of fake sensations. It dissolved into a puddle, unable to distinguish self from illusion. The monster vanished into a dream of salt.",
          "ジェリーの単純な思考は、洪水のように押し寄せる偽の感覚に耐えられなかった。自己と世界の境界を失い、怪物は音もなく冷たい液だまりへと溶け落ちた。形なき魔物は、塩の夢の中に消えた。",
          "果冻怪那简单的思考无法承受洪水般涌来的虚假感觉。失去了自我与世界的边界，怪物无声地融化成了一滩冰冷的液体。无形之魔消失在了盐之梦中。"),
    "K": ("The kobold followed a trail of decoy footsteps into a spike pit. It barked at the air until its lungs gave out. The tribal warrior was defeated by a ghost it couldn't smell.",
          "コボルドは偽りの足跡を追い、密かに仕掛けられた死の罠へと飛び込んだ。存在しない敵に向かって吠え続け、誇り高き犬戦士は空虚に力尽きた。嗅覚すら欺く亡霊に、勝機はなかった。",
          "狗头人追逐着虚假的足迹，跳入了秘密设置的死亡陷阱。它对着不存在的敌人不断吠叫，高傲的犬战士在虚无中耗尽了力气。在连嗅觉都能欺骗的亡灵面前，根本没有胜机。"),
    "L": ("The lizard's heat pits were fooled by decoy fireballs. It struck at shadows while the true threat closed in from the cold. The reptile's instinct was its undoing.",
          "リザードの赤外線検知は、周囲に展開された擬似的な熱源に惑わされた。幻の熱に向かって牙を剥く間に、真の脅威が背後の冷気から奴を仕留めた。野生の直感こそが、最大の罠となった。",
          "蜥蜴的红外线检测被周围展开的拟似热源所迷惑。正当它向着幻觉热源露出獠牙时，真正的威胁从背后的冷气中将其干掉。野性的直觉反倒成了最大的陷阱。"),
    "M": ("The mummy saw its ancient kingdom restored for a fleeting moment. It reached out for royalty, only to crumble into sand. Its eternal wandering ended in a cruel, beautiful lie.",
          "マミーは刹那の間に、かつての栄華極まる王国の幻視を見た。玉座へ手を伸ばした瞬間、その肉体は数千年の時を越えて砂へと瓦解した。永遠の彷徨は、残酷なほど美しい嘘と共に終わった。",
          "木乃伊在那一刹那看到了曾经繁荣至极的王国幻象。在向王座伸出手的瞬间，它的肉体跨越数千年时光崩解成了沙土。永恒的徘徊伴随着残酷而美丽的谎言结束了。"),
    "N": ("The naga was mesmerized by a reflection of her own beauty. She lost her focus and was struck down while admiring the phantom. The serpent's vanity led to its silent end.",
          "ナーガは水面に映る、自身の完璧な美しさを模した幻影に心奪われた。警戒が感嘆に変わった隙を突かれ、美しき賢者は永遠の眠りについた。人面蛇の虚栄は、哀れな沈黙によって幕を閉じた。",
          "纳迦被水面上倒映出的、模仿自身完美美貌的幻影夺走了心神。在警戒化为感叹的空档，美丽的贤者陷入了永眠。人面蛇的虚荣在一声可怜的沈默中落下了帷幕。"),
    "O": ("The orc swung its axe at a giant shadow that offered no resistance. It screamed in rage until its spirit broke from fighting nothing. The brute's strength was useless against a dream.",
          "オークは手応えのない巨大な影に向かって、狂ったように斧を振るい続けた。無を相手に体力を使い果たし、蛮勇の徒は自らの絶叫と共に力尽きた。怪力は、夢という名の城壁に阻まれた。",
          "兽人朝着那毫无手感的巨影，如发狂般不断挥舞战斧。它由于对手是虚无而耗尽了体力，蛮勇之徒伴随着自身的绝叫力竭倒下。怪力被名为梦境的城墙挡住了。"),
    "P": ("The pixie's light was absorbed by a deeper, more convincing illusion. She became a prisoner of her own specialty, fading into the dark. The trickster was outclassed by the master of fakes.",
          "ピクシーの放つ光は、より深く、説得力のある幻影に飲み込まれてしまった。自らの得意分野で囚われの身となった彼女は、闇の中に静かに消えた。悪戯の天才は、偽物の本物の前に敗れ去った。",
          "小仙女放射出的光芒被更深邃、更有说服力的幻影所吞噬。在自己所擅长的领域沦为阶下囚的她，静静地消失在黑暗中。恶作剧的天才败在了伪物的真物面前。"),
    "Q": ("The coeurl's electromagnetic sense processed millions of fake signals at once. Its brain short-circuited trying to find the true heartbeat. The high-speed hunter died from calculation failure.",
          "クアールの超感覚が、数百万の偽りの電磁信号を一度に処理し、パンクした。真実の鼓動を求める余り脳が短絡し、獣は音もなくその場に倒れた。高速の狩人は、計算の誤りによって死した。",
          "夸尔的超感官由于一次性处理了数百万个虚假电磁信号而陷入瘫痪。因过度寻求真相的心跳导致大脑短路，野兽无声地倒在当场。高速猎手死于计算错误。"),
    "R": ("The rat swarm chased a phantom grain pile into a deep river. They followed the leader into a watery grave of illusions. The pack's instinct was drowned in a logical trap.",
          "ラットの群れは幻の食糧を追い、誘われるまま深い濁流へと身を投げた。一匹の疑いもなくリーダーに続き、彼らは幻想の水槽で最期を迎えた。群れの直感は、論理的な罠の中に沈んだ。",
          "鼠群追逐着幻觉中的粮食，受诱导而跃入湍急的浊流。毫无疑虑地跟随首领，它们在幻想的水槽中迎来了终结。鼠群的直觉沉没在逻辑陷阱之中。"),
    "S": ("The slime tried to envelope a fire that felt cold and wet. It was confused by the sensory paradox and fell apart. The gelatinous monster dissolved into a dream of logic.",
          "スライムは、冷たく湿った感触を持つ幻の火を飲み込もうとした。感覚のパラドックスに処理が追いつかず、肉体は崩壊し、水たまりへと還った。怪物は、論理という名の夢の中に溶けた。",
          "史莱姆试图吞噬一团带有冰冷潮湿感的幻觉之火。由于处理无法跟上感觉的悖论，肉体崩坏，还原成了水洼。怪物融化在名为逻辑的梦境中。"),
    "T": ("The troll regenerates wounds of a phantom blade that never hit. It exhausted its vitality healing shadows until its heart stopped. The giant fell to an illness of the mind.",
          "トロールは、一度も触れていない幻の刃による傷を、必死に再生し続けた。影を癒すために生命力を使い果たし、巨人は自らの意思で鼓動を止めた。巨躯は、精神の病という凶刃に倒れた。",
          "巨魔拼命地再生着那从未触及身体的幻之刃留下的伤口。为了愈合影子而耗尽了生命力，巨人凭自身的意志停止了心跳。庞大的身躯倒在名为精神之疾的凶刃之下。"),
    "U": ("The undead were lured into a cage of holy light that was only a memory. They reached for salvation only to be erased from existence. Their lingering regret was burned away by a dream of the sun.",
          "アンデッドは、記憶の中にのみ存在する聖なる光の檻へと誘い込まれた。救いを求めて光に触れた瞬間、彼らの未練は浄化され、魂は虚空に消えた。亡霊は、太陽の夢によって焼き尽くされた。",
          "不死族被诱入了一座仅存在于记忆中的神圣光之牢笼。在寻求救赎并触碰光芒的瞬间，它们的留恋被净化，灵魂消失在虚空中。亡灵被太阳之梦燃尽了。"),
    "V": ("The vampire struck at a reflection of himself and shattered his own essence. He died cursing the vanity that made him look too long into the dark. The noble met a transparent end.",
          "ヴァンパイアは鏡合わせのように現れた自身の虚像を攻撃し、その本質を自ら砕いた。闇を覗き込みすぎた己の虚栄を呪いながら、夜の王は砂へと還った。貴族は、透明な終焉を迎えた。",
          "吸血鬼攻击了如镜像般出现的自身虚像，亲手粉碎了自己的本质。在诅咒着因过度窥视黑暗而产生的虚荣的同时，夜之王回归了尘土。贵族迎来了透明的终焉。"),
    "X": ("Xalthis's eyes each saw a different world of horror. It spun in circles until its legs tangled and broke. The multi-legged terror was defeated by its own perspective.",
          "ザルティスの無数の複眼は、それぞれ別々の絶望の世界を映し出した。逃げ場を求めて回転し続けた身体は、自らの多足に絡まって無残に折れた。多足の恐怖は、自らの視界に溺れた。",
          "扎尔提斯无数复眼的每一个都映照出了不同的绝望世界。为了寻找生路而不断旋转的身体被自己的多肢缠绕，凄惨地折断了。多肢的恐怖溺死在自身的视野中。"),
    "Y": ("The yeti chased a warm spring that wasn't there. It walked deep into a whiteout of its own hope until it froze. The king of the peaks died dreaming of a warmth that never existed.",
          "イエティは存在しない暖かい春を追い、自身の希望が作り出した吹雪の中へ消えた。ホワイトアウトの向こう側に幻の熱を求め、巨人は静かに凍りついた。嶺の王は、ありもしない温もりを夢見て絶命した。",
          "雪人追逐着不存在的暖春，消失在由自身希望产生的雪暴中。在白茫茫的视野另一侧追求幻之热，巨人静静地冻结了。岭之王梦见了不存在的温情而毙命。"),
    "Z": ("The zombie saw its living family in a blur of rotting memory. It reached out only to be struck down by the truth. The dead were finally given a peaceful lie to die in.",
          "ゾンビは腐食した記憶の混濁の中で、かつての家族の姿を見た。救いを求めて手を伸ばしたその隙に、死者は永遠の眠りへと導かれた。動く死体には、最期に穏やかな嘘だけが与えられた。",
          "僵尸在腐蚀记忆的混浊中，看到了曾经家人的身影。在它寻求救赎并伸出手的空档，死者被引导向了永恒的眠梦。给那会动的尸体，最后仅给予了一场安稳的谎言。")
}

# Napalm Skill Flavor Texts (Wins and Losses combined list)
napalm_data = {
    "A": ("The ant nest was incinerated by the sticky, burning gel. The fire clung to their shells as they tried to flee underground. The colony was turned into a small mountain of ash.",
          "粘着性の高い燃え盛るジェルが、アリの巣を瞬時に地獄へと変えた。地下へと逃げ惑う虫たちの背中に火が絡みつき、逃げ場を奪う。群れは、熱風の中に消える小さな灰の山となった。",
          "高粘性的燃烧凝胶瞬间将蚁穴变成了地狱。火苗缠绕在向地下逃窜的昆虫背上，夺走了其退路。蚁群在热浪中化作了一座消逝的微小灰烬山。"),
    "B": ("The bat was engulfed in a fireball and fell like a falling star. The gel burned so hot it didn't even leave bones. The sky was lit by the monster's final, fiery scream.",
          "火球に飲み込まれたコウモリは、燃え盛る流星のごとく墜落した。ジェルの熱は骨さえを焼き尽くし、夜空に異臭だけを残した。魔物の最期は、闇を切り裂く一筋の火柱となった。",
          "被火球吞没的蝙蝠犹如燃烧的流星般坠落。凝胶的热量连骨头都能烧尽，只在夜空留下异臭。魔物的终焉化作了一道划破黑暗的火柱。"),
    "C": ("The cobra's low position made it take the full force of the napalm. It writhed in the burning puddle as its scales melted into sludge. The venomous snake was cooked in its own home.",
          "地面を這うコブラの低さは、ナパームの熱を逃さず受け止める結果となった。溶け出した鱗が泥のようになり、魔物は灼熱の池で最期まで悶えた。猛毒の蛇は、自らの居場所で焼き尽くされた。",
          "在地面爬行的眼镜蛇由于身位极低，不得不全盘承受纳帕姆的热量。熔化的鳞片变得像泥一样，魔物在灼热的池水中痛苦挣扎至最后一刻。剧毒之蛇在自己的栖息地被烧尽了。"),
    "D": ("The dragon's resistance was overcome by a fire that wouldn't go out. It roared in surprise as the chemical flame clung to its legendary hide. The king of fire met a hotter end.",
          "ドラゴンの火耐性をもってしても、消えることのない化学の炎は防げなかった。伝説の皮に絡みつく不浄な火に怪物は驚愕し、空虚な咆哮を上げた。火の王は、より熾烈な熱の中に沈んだ。",
          "即使拥有巨龙的火焰抗性，也无法抵御永不熄灭的化学之火。怪物对缠绕在传说皮革上的不净之火感到惊愕，发出了虚无的咆哮。火之王沉没在了更为炽烈的热浪中。"),
    "E": ("The wood spirit ignited instantly and became a massive, living torch. The forest echoed with the sound of centuries of life burning in minutes. The guardian fell and brought silence.",
          "古の精霊は瞬時に火だるまとなり、巨大な「生ける松明」と化した。数世紀の生命が数分で灰になる音が、森の奥深くまで響き渡った。守護者が崩れ落ちる時、緑の楽園は静寂に包まれた。",
          "古老之灵瞬间化为了火人，变成了巨大的“活体火炬”。数个世纪的生命在几分钟内化为灰烬的声音，在森林深处四处回响。当守护者倒下时，森林乐园陷入了沉寂。"),
    "F": ("The fly vanished in a localized firestorm before it could buzz once. The air itself became a lethal weapon of burning gel. Not a single trace of the insect remained.",
          "ハエは一度の羽音を立てる暇もなく、局所的な火炎嵐の中に消えた。空気が焼けたジェルの熱気で充満し、小さな生命を瞬時に奪い去った。そこに虫がいたという証拠さえ、熱の中へと消えた。",
          "苍蝇连发出一次翅鸣的时间都没有，就消失在局部的火焰风暴中。空气中弥漫着燃烧凝胶的热气，瞬间夺走了微小的生命。连那里曾有过昆虫的证据，都消失在热浪中了。"),
    "G": ("The goblin nest was filled with a fire that crawled like a snake. They screamed as the sticky flames covered their cowardly bodies. Their greed died in the heat of a chemical inferno.",
          "ゴブリンの住処は、蛇のように地を這う炎によって満たされた。卑屈な身体に絡みつく粘着性の火に、奴らは絶叫の合唱を上げた。強欲な魔物の最後は、化学の地獄が生んだ灰に過ぎなかった。",
          "哥布林的栖息地被如蛇般在地面爬行的火焰所填满。粘稠的火焰缠绕在卑下的身体上，它们发出了绝叫的合唱。贪婪魔物的最后，不过是化学地狱产生的灰烬。"),
    "H": ("Extreme heat from the napalm scorched the harpy's wings in mid-air. She fell into the burning puddle and was consumed by the relentless gel. Her cry of vanity was silenced by the fire.",
          "ナパームの激しい熱が、上空を舞うハーピーの翼を一瞬で焼き払った。燃え盛る池へと墜ちた彼女を、容赦のないジェルが呑み込んだ。虚栄に満ちた叫びは、火を爆ぜる音に掻き消された。",
          "纳帕姆剧烈的热量瞬间烧毁了在空中飞舞的哈皮的双翼。她坠入燃烧的池塘，无情的凝胶将其吞噬。充斥着虚荣的悲鸣，淹没在火焰的爆裂声中。"),
    "I": ("The imp saw its magical pranks turned into a literal hell on earth. It shrieked as its demonic hide bubbled under the chemical flame. The trickster's laughter ended in a burning gasp.",
          "インプは自らの悪魔的な悪戯が、文字通りの地獄へと変貌する様を目撃した。化学の火に焼かれた奴の皮膚は泡立ち、悪戯っ子の笑い声は悲鳴に変わった。魔界の住人は、焦熱の苦しみの中に沈んだ。",
          "小恶魔目睹了其恶魔般的恶作剧变为字面意义上的尘世地狱。被化学之火焚烧的皮肤冒起了泡，捣蛋鬼的笑声变成了尖叫。魔界居民沉没在了焦热的苦难中。"),
    "J": ("The jelly's water content vaporized in an explosion of steam. What was left of the slime was dried out and burned to a crisp. The monster turned into a hard, charred crust.",
          "ジェリーの水分が、ナパームの熱によって爆発的な水蒸気となり霧散した。残された不浄な肉体も乾燥し、カリカリに焼き尽くされた。怪物は、床に転がるただの黒い炭塊へと成り果てた。",
          "果冻怪的水分由于纳帕姆的热量化作爆发性的水蒸气消散了。剩下那不净的肉体也随之干燥，被烧得焦脆。怪物变成了地板上一块平凡的黑炭。"),
    "K": ("The kobold warrior found no honor in a death from chemical fire. It rolled on the ground only to have the gel stick closer. Its yelps were cut short as the air vanished.",
          "コボルドの戦士にとって、化学の炎による死に名誉など微塵もなかった。必死に地面を転がるが、火のついたジェルはさらに広がるばかり。鳴き声は絶たれ、最後には静かな焦げ跡だけが残った。",
          "对于狗头人战士来说，死于化学之火根本没有半点名誉。它拼命在地上翻滚，但着火的凝胶却进一步扩散。哀鸣戛然而止，最后只剩下了寂静的焦痕。"),
    "L": ("The lizard's scales failed to protect its inner flesh from the persistent heat. It hissed in agony as its cold blood was brought to a boil. The silent predator met a noisy, burning end.",
          "堅牢な鱗も、身体の芯まで焼き尽くす執拗な熱からは守ってくれなかった。冷血な血液が沸騰し、リザードは苦悶の叫びを上げた。沈黙の捕食者は、皮肉にも騒がしい焼死を告げられた。",
          "坚固的鳞片也没能保护它免受焚烧至身体深处的执拗热量。冷血的血液沸腾了，蜥蜴发出了痛苦的哀叫。沈默的掠食者讽刺地迎来了嘈杂的烧死结局。"),
    "M": ("The mummy caught fire like dry paper and burned to a white ash. Its centuries-old curse offered no resistance to the modern weapon. The dead was finally granted an incinerated rest.",
          "マミーの身体は乾いた紙のように火がつき、一瞬で白い灰へと変わった。数千年の呪縛も、近代兵器の圧倒的な火力の前には無力だった。死者はついに、焼き尽くされるという救いを得た。",
          "木乃伊的身体像干纸一样着了火，瞬间化为白灰。数千年的束缚在现代武器压倒性的火力面前也无济于事。死者终于得到了被烧尽这一解脱。"),
    "N": ("The naga's water magic was boiled away before it could be cast. She writhed in the flames as the gel ate her beautiful serpent skin. The wise one was reduced to a tragic, charred form.",
          "ナーガの水魔法が発動する前に、ナパームの熱が周囲を沸騰させた。美しい蛇の皮を焼き焦がすジェルに、彼女は悶え苦しみ絶命した。賢き者は、見る影もない無惨な焼死体へと変貌した。",
          "在纳迦的水魔法发动之前，纳帕姆的热量就令周围沸腾了。由于凝胶烧焦了美丽的蛇皮，她在痛苦挣扎中毙命。聪慧者化为了面目全非、凄惨无比的焦尸。"),
    "O": ("The orc charged through the initial fire but was slowed as the gel burned deeper. Its grunt transformed into a roar of pain until it fell as a blackened mass. The grunt's brute force failed.",
          "オークは最初の炎を突き破って突進したが、ジェルが深く焼くにつれその足は鈍った。蛮勇の咆哮は苦悶の叫びへと変わり、最後には巨大な炭塊となった。怪力は、熱という冷徹な暴力に屈した。",
          "兽人冲破最初的火焰发起了突击，但随着凝胶烧得愈深，它的脚步变得迟缓。蛮勇的咆哮变成了痛苦的哀鸣，最后变成了一块巨大的炭。怪力向名为热量的冷彻暴力屈服了。"),
    "P": ("The pixie's wings sparked and melted in the intense chemical heat. She fell from the sky, her magical light extinguished by the crude, violent fire. The forest's trickster met a heavy, burning end.",
          "ピクシーの繊細な翼が、激しい熱によって一瞬で溶け落ちた。空から堕ちる彼女を、魔法の光さえも見捨て、無慈悲な炎が呑み込んだ。悪戯好きの精霊の時間は、熱風の中に永遠に閉ざされた。",
          "小仙女纤细的双翼在剧烈的热量下瞬间熔化。魔法之光也抛弃了从空中坠落的她，无情的火焰将其吞没。爱开玩笑的精灵的时间，永远封闭在了热浪中。"),
    "Q": ("The coeurl's field couldn't stop the spread of physical burning gel. Lightning flashed in vain as the beast was consumed by the chemical fire. The high-speed beast became a glowing ember.",
          "クアールの電磁場も、物理的なジェルの延焼を防ぐことはできなかった。獣は化学の火に呑まれ、闇夜に虚しい雷を散らせながら絶命した。高速の捕食者は、静かに燃える残り火へと変わった。",
          "夸尔的电磁场无法阻止物理性凝胶的延烧。野兽被化学之火吞没，在黑夜中散射着徒劳的雷光毙命。高速掠食者变成了静静燃烧的余烬。"),
    "R": ("The rat swarm was incinerated by a blanket of fire that covered the path. Their numbers provided no protection against the all-consuming gel. The pack vanished in a singular fiery breath.",
          "退路を塞ぐ炎の壁が、ラットの群れを根こそぎ焼き尽くした。数の暴力は、全てを呑み込むジェルの前には何の意味も持たなかった。群れは、一つの巨大な火柱となって消え去った。",
          "封锁退路的火墙将鼠群斩草除根地烧尽。在吞噬一切的凝胶面前，数量的暴力没有任何意义。鼠群化作一根巨大的火柱消逝了。"),
    "S": ("The slime absorbed the gel only to have its entire body ignite from within. It dissolved into a boiling sludge until only a black stain remained. The monster met a thermal collapse.",
          "スライムはジェルを取り込んだが、それは内側から自身を燃やし尽くす毒となった。怪物は煮え繰りかえる泥となり、最後には黒い染みだけが残った。魔物は、熱による完全な崩壊を迎えた。",
          "史莱姆吸收了凝胶，但这成了从内部将其烧尽的剧毒。怪物变成了沸腾的烂泥，最后只剩下了一抹黑色的污迹。魔物迎来了由于热量导致的完全崩坏。"),
    "T": ("The troll's legendary healing struggled against a fire that wouldn't stop burning. It reached its limit and finally succumbed to the heat. The giant died in an eternal column of fire.",
          "トロールの再生能力も、絶え間なく燃え続けるナパームの前には無力だった。極限を超えた怪物の肉体は崩壊し、最後には命の火を絶たれた。巨人は、永遠に続く焦熱の柱の中に消えた。",
          "巨魔的再生能力在持续燃烧的纳帕姆面前也无济于事。超越极限的怪物肉体崩坏了，最后命之火熄灭。巨人在永无止境的焦热之柱中消失了。"),
    "U": ("The undead's ghostly form was refined into ash by the purifying chemical fire. Their spiritual presence was incinerated until nothing but peace remained. The shadow was erased by a light too intense.",
          "実体のないアンデッドさえ、ナパームの熾烈な熱には抗えなかった。死者の残留思念までもが焼き尽くされ、後には静寂な灰だけが残った。亡霊は、あまりに強烈な「生の光」に消滅させられた。",
          "即使是没有实体的亡灵，也无法抗拒纳帕姆炽烈的热量。连死者的残留思念都被烧尽，只余下寂静的灰烬。亡灵被过于强烈的“生之光”消灭了。"),
    "V": ("The vampire's inhuman speed couldn't outrun a fire that covered the whole room. He died gracefully, his noble form turning to a fine white ash in seconds. The night was ended by a man-made sun.",
          "ヴァンパイアの超人的な速度も、部屋を埋め尽くすナパームからは逃げられなかった。闇の貴族は優雅に微笑み、数秒で白い塵へと還った。夜の王の最期は、人工の太陽によって照らされた。",
          "即使拥有吸血鬼超人般的速度，也无法从填满房间的纳帕姆中逃脱。黑暗贵族优雅地微笑着，在数秒内重归白尘。夜之王的终焉被人工太阳照亮了。"),
    "W": ("The wolf pack's territory was turned into a burning trap. Their coordinated barks were cut short by the roar of the chemical flames. The hunters were consumed in the heat of a tactical fire.",
          "ウルフの縄張りは、死のナパームによって灼熱の罠へと変貌した。群れの誇り高き咆哮は火の海に沈み、獣たちは炭へと変わった。森の狩人は、近代戦術の熱き暴力に食い尽くされた。",
          "狼群的领地由于致命的纳帕姆而变成了灼热的陷阱。狼群高傲的咆哮沉入火海，野兽们变成了炭。森林猎手被现代战术的热血暴力吞噬了。"),
    "X": ("Xalthis's many legs only provided more surface area for the burning gel to cling. It struggled in a frantic dance of death until it was incinerated completely. The multi-legged terror died in the fire.",
          "ザルティスの多くの脚は、執拗に絡みつくジェルのための「薪」でしかなかった。狂乱の死の舞踏を踊りながら、魔物は紅蓮の炎の中で静止した。多足の恐怖は、化学の地獄に沈んだ。",
          "扎尔提斯的众多肢体，成了供执拗缠绕凝胶燃烧的“柴火”。它跳着狂乱的死亡之舞，在红莲之火中停止了。多肢的恐怖沈没在化学地狱中。"),
    "Y": ("The yeti's frost failed to cool the burning gel clinging to its fur. It became a mountain of fire in its cold domain before it finally fell. The ice giant was melting away in a chemical sun.",
          "イエティの放つ冷気も、毛皮に執拗に絡みつく灼熱のジェルを消せなかった。氷の巨人は火の山と化し、その極寒の国で静かに絶命した。雪山の主は、人工の太陽の下で溶け去った。",
          "雪人散发的冷气也无法熄灭执拗缠绕在毛皮上的灼热凝胶。冰巨人化作火山，在其极寒国度静静地毙命。雪山之主在人工太阳下消融了。"),
    "Z": ("The zombie was incinerated as the sticky fire ate through its dead flesh. The gel ensured that no part of the undead would rise again. The living corpse met a final, scorching peace.",
          "ナパームの粘着火がゾンビの腐肉を食らい、その存在を根源から抹消した。ジェルは死体が二度と動き出さぬよう、全てを純白の灰に変えた。動く死体は、ついに焼き尽くされる救いを得た。",
          "纳帕姆的粘着火吞噬了僵尸的腐肉，从根源上抹杀了其存在。凝胶确保尸体不会再次动弹，将一切化为了纯白的灰烬。会动的尸体终于得到了被烧尽的救赎。")
}

# Execute localization additions
def main():
    # Skill names and generic messages were added previously via command line
    # (assuming they were successful and included "Attacked with [Skill] and won!")

    # Gravity
    process_skill("Gravity", gravity_data, win_status["Gravity"])
    # Illusion
    process_skill("Illusion", illusion_data, win_status["Illusion"])
    # Napalm
    process_skill("Napalm", napalm_data, win_status["Napalm"])

if __name__ == "__main__":
    main()
