class_name EnemyData
extends RefCounted

const ENEMIES = {
	"A": {"name": "Ant", "level": 1, "min_floor": 1, "max_floor": 2, "agro_range": 3, "skill": "Bite"},
	"B": {"name": "Bat", "level": 1, "min_floor": 1, "max_floor": 2, "agro_range": 3, "skill": "Bite"},
	"C": {"name": "Cobra", "level": 1, "min_floor": 1, "max_floor": 2, "agro_range": 3, "skill": "Tackle"},
	"D": {"name": "Dragon", "level": 1, "min_floor": 1, "max_floor": 2, "agro_range": 3, "skill": "Scratch"},
	"E": {"name": "Ent", "level": 1, "min_floor": 1, "max_floor": 2, "agro_range": 3, "skill": "Scratch"},
	"F": {"name": "Fly", "level": 2, "min_floor": 2, "max_floor": 3, "agro_range": 4, "skill": "Scratch"},
	"G": {"name": "Goblin", "level": 2, "min_floor": 2, "max_floor": 3, "agro_range": 4, "skill": "Bite"},
	"H": {"name": "Harpy", "level": 2, "min_floor": 2, "max_floor": 3, "agro_range": 4, "skill": "Venom"},
	"I": {"name": "Imp", "level": 2, "min_floor": 2, "max_floor": 3, "agro_range": 4, "skill": "Bite"},
	"J": {"name": "Jelly", "level": 2, "min_floor": 2, "max_floor": 3, "agro_range": 4, "skill": "Venom"},
	"K": {"name": "Kobold", "level": 3, "min_floor": 3, "max_floor": 4, "agro_range": 5, "skill": "Pounce"},
	"L": {"name": "Lizard", "level": 3, "min_floor": 3, "max_floor": 4, "agro_range": 5, "skill": "Bite"},
	"M": {"name": "Mummy", "level": 3, "min_floor": 3, "max_floor": 4, "agro_range": 5, "skill": "Bite"},
	"N": {"name": "Naga", "level": 3, "min_floor": 3, "max_floor": 4, "agro_range": 5, "skill": "Bite"},
	"O": {"name": "Orc", "level": 3, "min_floor": 3, "max_floor": 4, "agro_range": 5, "skill": "Scratch"},
	"P": {"name": "Pixie", "level": 4, "min_floor": 4, "max_floor": 5, "agro_range": 6, "skill": "Scratch"},
	"Q": {"name": "Coeurl", "level": 4, "min_floor": 4, "max_floor": 5, "agro_range": 6, "skill": "Venom"},
	"R": {"name": "Rat", "level": 4, "min_floor": 4, "max_floor": 5, "agro_range": 6, "skill": "Venom"},
	"S": {"name": "Slime", "level": 4, "min_floor": 4, "max_floor": 5, "agro_range": 6, "skill": "Bite"},
	"T": {"name": "Troll", "level": 4, "min_floor": 4, "max_floor": 5, "agro_range": 6, "skill": "Venom"},
	"U": {"name": "Undead", "level": 5, "min_floor": 5, "max_floor": 5, "agro_range": 7, "skill": "Scratch"},
	"V": {"name": "Vampire", "level": 5, "min_floor": 5, "max_floor": 5, "agro_range": 7, "skill": "Venom"},
	"W": {"name": "Wolf", "level": 5, "min_floor": 5, "max_floor": 5, "agro_range": 7, "skill": "Pounce"},
	"X": {"name": "Xalthis", "level": 5, "min_floor": 5, "max_floor": 5, "agro_range": 7, "skill": "Scratch"},
	"Y": {"name": "Yeti", "level": 5, "min_floor": 5, "max_floor": 5, "agro_range": 7, "skill": "Pounce"},
	"Z": {"name": "Zombie", "level": 5, "min_floor": 5, "max_floor": 5, "agro_range": 7, "skill": "Venom"},
}
