class_name EnemyData
extends RefCounted

const ENEMIES = {
    "A": {"name": "アント", "level": 1, "min_floor": 1, "max_floor": 2, "agro_range": 3, "skill": "噛みつき"},
    "B": {"name": "バット", "level": 1, "min_floor": 1, "max_floor": 2, "agro_range": 3, "skill": "噛みつき"},
    "C": {"name": "コブラ", "level": 1, "min_floor": 1, "max_floor": 2, "agro_range": 3, "skill": "体当たり"},
    "D": {"name": "ドラゴン", "level": 1, "min_floor": 1, "max_floor": 2, "agro_range": 3, "skill": "ひっかき"},
    "E": {"name": "エント", "level": 1, "min_floor": 1, "max_floor": 2, "agro_range": 3, "skill": "ひっかき"},
    "F": {"name": "フライ", "level": 2, "min_floor": 2, "max_floor": 3, "agro_range": 4, "skill": "ひっかき"},
    "G": {"name": "ゴブリン", "level": 2, "min_floor": 2, "max_floor": 3, "agro_range": 4, "skill": "噛みつき"},
    "H": {"name": "ハーピー", "level": 2, "min_floor": 2, "max_floor": 3, "agro_range": 4, "skill": "毒液"},
    "I": {"name": "インプ", "level": 2, "min_floor": 2, "max_floor": 3, "agro_range": 4, "skill": "噛みつき"},
    "J": {"name": "ジェリー", "level": 2, "min_floor": 2, "max_floor": 3, "agro_range": 4, "skill": "毒液"},
    "K": {"name": "コボルド", "level": 3, "min_floor": 3, "max_floor": 4, "agro_range": 5, "skill": "飛びかかり"},
    "L": {"name": "リザード", "level": 3, "min_floor": 3, "max_floor": 4, "agro_range": 5, "skill": "噛みつき"},
    "M": {"name": "マミー", "level": 3, "min_floor": 3, "max_floor": 4, "agro_range": 5, "skill": "噛みつき"},
    "N": {"name": "ナーガ", "level": 3, "min_floor": 3, "max_floor": 4, "agro_range": 5, "skill": "噛みつき"},
    "O": {"name": "オーク", "level": 3, "min_floor": 3, "max_floor": 4, "agro_range": 5, "skill": "ひっかき"},
    "P": {"name": "ピクシー", "level": 4, "min_floor": 4, "max_floor": 5, "agro_range": 6, "skill": "ひっかき"},
    "Q": {"name": "クアール", "level": 4, "min_floor": 4, "max_floor": 5, "agro_range": 6, "skill": "毒液"},
    "R": {"name": "ラット", "level": 4, "min_floor": 4, "max_floor": 5, "agro_range": 6, "skill": "毒液"},
    "S": {"name": "スライム", "level": 4, "min_floor": 4, "max_floor": 5, "agro_range": 6, "skill": "噛みつき"},
    "T": {"name": "トロル", "level": 4, "min_floor": 4, "max_floor": 5, "agro_range": 6, "skill": "毒液"},
    "U": {"name": "アンデッド", "level": 5, "min_floor": 5, "max_floor": 5, "agro_range": 7, "skill": "ひっかき"},
    "V": {"name": "ヴァンパイア", "level": 5, "min_floor": 5, "max_floor": 5, "agro_range": 7, "skill": "毒液"},
    "W": {"name": "ウルフ", "level": 5, "min_floor": 5, "max_floor": 5, "agro_range": 7, "skill": "飛びかかり"},
    "X": {"name": "ザルティス", "level": 5, "min_floor": 5, "max_floor": 5, "agro_range": 7, "skill": "ひっかき"},
    "Y": {"name": "イエティ", "level": 5, "min_floor": 5, "max_floor": 5, "agro_range": 7, "skill": "飛びかかり"},
    "Z": {"name": "ゾンビ", "level": 5, "min_floor": 5, "max_floor": 5, "agro_range": 7, "skill": "毒液"},
}
