class_name ItemData
extends RefCounted

const SKILLS = [
    "殴る",
    "斬る",
    "突く",
    "撃つ",
    "燃やす",
    "凍らせる",
    "罠",
    "呪う",
    "祈る",
    "逃げる",
    "説得",
    "隠れる",
    "騙す",
    "威圧",
    "媚びる",
    "買収",
    "毒",
    "歌う",
    "踊る",
    "気合",
]

const COMBAT_RESULTS = {
    "殴る": {
        "A": { "win": true, "message": "殴るで攻撃し、勝利した！" },
        "B": { "win": true, "message": "殴るで攻撃し、勝利した！" },
        "C": { "win": true, "message": "殴るで攻撃し、勝利した！" },
        "D": { "win": true, "message": "殴るで攻撃し、勝利した！" },
        "E": { "win": true, "message": "殴るで攻撃し、勝利した！" },
        "F": { "win": true, "message": "殴るで攻撃し、勝利した！" },
        "G": { "win": true, "message": "殴るで攻撃し、勝利した！" },
        "H": { "win": true, "message": "殴るで攻撃し、勝利した！" },
        "I": { "win": true, "message": "殴るで攻撃し、勝利した！" },
        "J": { "win": true, "message": "殴るで攻撃し、勝利した！" },
        "K": { "win": true, "message": "殴るで攻撃し、勝利した！" },
        "L": { "win": false, "message": "殴るが効かず、敗北した..." },
        "M": { "win": true, "message": "殴るで攻撃し、勝利した！" },
        "N": { "win": false, "message": "殴るが効かず、敗北した..." },
        "O": { "win": false, "message": "殴るが効かず、敗北した..." },
        "P": { "win": false, "message": "殴るが効かず、敗北した..." },
        "Q": { "win": false, "message": "殴るが効かず、敗北した..." },
        "R": { "win": false, "message": "殴るが効かず、敗北した..." },
        "S": { "win": false, "message": "殴るが効かず、敗北した..." },
        "T": { "win": false, "message": "殴るが効かず、敗北した..." },
        "U": { "win": false, "message": "殴るが効かず、敗北した..." },
        "V": { "win": false, "message": "殴るが効かず、敗北した..." },
        "W": { "win": false, "message": "殴るが効かず、敗北した..." },
        "X": { "win": false, "message": "殴るが効かず、敗北した..." },
        "Y": { "win": false, "message": "殴るが効かず、敗北した..." },
        "Z": { "win": false, "message": "殴るが効かず、敗北した..." },
    },
    "斬る": {
        "A": { "win": true, "message": "斬るで攻撃し、勝利した！" },
        "B": { "win": true, "message": "斬るで攻撃し、勝利した！" },
        "C": { "win": true, "message": "斬るで攻撃し、勝利した！" },
        "D": { "win": true, "message": "斬るで攻撃し、勝利した！" },
        "E": { "win": true, "message": "斬るで攻撃し、勝利した！" },
        "F": { "win": true, "message": "斬るで攻撃し、勝利した！" },
        "G": { "win": false, "message": "斬るが効かず、敗北した..." },
        "H": { "win": true, "message": "斬るで攻撃し、勝利した！" },
        "I": { "win": true, "message": "斬るで攻撃し、勝利した！" },
        "J": { "win": true, "message": "斬るで攻撃し、勝利した！" },
        "K": { "win": true, "message": "斬るで攻撃し、勝利した！" },
        "L": { "win": true, "message": "斬るで攻撃し、勝利した！" },
        "M": { "win": true, "message": "斬るで攻撃し、勝利した！" },
        "N": { "win": true, "message": "斬るで攻撃し、勝利した！" },
        "O": { "win": false, "message": "斬るが効かず、敗北した..." },
        "P": { "win": true, "message": "斬るで攻撃し、勝利した！" },
        "Q": { "win": true, "message": "斬るで攻撃し、勝利した！" },
        "R": { "win": true, "message": "斬るで攻撃し、勝利した！" },
        "S": { "win": true, "message": "斬るで攻撃し、勝利した！" },
        "T": { "win": false, "message": "斬るが効かず、敗北した..." },
        "U": { "win": true, "message": "斬るで攻撃し、勝利した！" },
        "V": { "win": true, "message": "斬るで攻撃し、勝利した！" },
        "W": { "win": false, "message": "斬るが効かず、敗北した..." },
        "X": { "win": false, "message": "斬るが効かず、敗北した..." },
        "Y": { "win": true, "message": "斬るで攻撃し、勝利した！" },
        "Z": { "win": false, "message": "斬るが効かず、敗北した..." },
    },
    "突く": {
        "A": { "win": false, "message": "突くが効かず、敗北した..." },
        "B": { "win": true, "message": "突くで攻撃し、勝利した！" },
        "C": { "win": true, "message": "突くで攻撃し、勝利した！" },
        "D": { "win": true, "message": "突くで攻撃し、勝利した！" },
        "E": { "win": true, "message": "突くで攻撃し、勝利した！" },
        "F": { "win": true, "message": "突くで攻撃し、勝利した！" },
        "G": { "win": true, "message": "突くで攻撃し、勝利した！" },
        "H": { "win": true, "message": "突くで攻撃し、勝利した！" },
        "I": { "win": true, "message": "突くで攻撃し、勝利した！" },
        "J": { "win": true, "message": "突くで攻撃し、勝利した！" },
        "K": { "win": false, "message": "突くが効かず、敗北した..." },
        "L": { "win": true, "message": "突くで攻撃し、勝利した！" },
        "M": { "win": false, "message": "突くが効かず、敗北した..." },
        "N": { "win": false, "message": "突くが効かず、敗北した..." },
        "O": { "win": true, "message": "突くで攻撃し、勝利した！" },
        "P": { "win": true, "message": "突くで攻撃し、勝利した！" },
        "Q": { "win": false, "message": "突くが効かず、敗北した..." },
        "R": { "win": false, "message": "突くが効かず、敗北した..." },
        "S": { "win": false, "message": "突くが効かず、敗北した..." },
        "T": { "win": false, "message": "突くが効かず、敗北した..." },
        "U": { "win": false, "message": "突くが効かず、敗北した..." },
        "V": { "win": false, "message": "突くが効かず、敗北した..." },
        "W": { "win": false, "message": "突くが効かず、敗北した..." },
        "X": { "win": false, "message": "突くが効かず、敗北した..." },
        "Y": { "win": false, "message": "突くが効かず、敗北した..." },
        "Z": { "win": false, "message": "突くが効かず、敗北した..." },
    },
    "撃つ": {
        "A": { "win": true, "message": "撃つで攻撃し、勝利した！" },
        "B": { "win": true, "message": "撃つで攻撃し、勝利した！" },
        "C": { "win": false, "message": "撃つが効かず、敗北した..." },
        "D": { "win": true, "message": "撃つで攻撃し、勝利した！" },
        "E": { "win": true, "message": "撃つで攻撃し、勝利した！" },
        "F": { "win": true, "message": "撃つで攻撃し、勝利した！" },
        "G": { "win": false, "message": "撃つが効かず、敗北した..." },
        "H": { "win": true, "message": "撃つで攻撃し、勝利した！" },
        "I": { "win": true, "message": "撃つで攻撃し、勝利した！" },
        "J": { "win": true, "message": "撃つで攻撃し、勝利した！" },
        "K": { "win": false, "message": "撃つが効かず、敗北した..." },
        "L": { "win": true, "message": "撃つで攻撃し、勝利した！" },
        "M": { "win": false, "message": "撃つが効かず、敗北した..." },
        "N": { "win": true, "message": "撃つで攻撃し、勝利した！" },
        "O": { "win": false, "message": "撃つが効かず、敗北した..." },
        "P": { "win": false, "message": "撃つが効かず、敗北した..." },
        "Q": { "win": true, "message": "撃つで攻撃し、勝利した！" },
        "R": { "win": false, "message": "撃つが効かず、敗北した..." },
        "S": { "win": false, "message": "撃つが効かず、敗北した..." },
        "T": { "win": false, "message": "撃つが効かず、敗北した..." },
        "U": { "win": false, "message": "撃つが効かず、敗北した..." },
        "V": { "win": false, "message": "撃つが効かず、敗北した..." },
        "W": { "win": false, "message": "撃つが効かず、敗北した..." },
        "X": { "win": false, "message": "撃つが効かず、敗北した..." },
        "Y": { "win": false, "message": "撃つが効かず、敗北した..." },
        "Z": { "win": false, "message": "撃つが効かず、敗北した..." },
    },
    "燃やす": {
        "A": { "win": true, "message": "燃やすで攻撃し、勝利した！" },
        "B": { "win": true, "message": "燃やすで攻撃し、勝利した！" },
        "C": { "win": true, "message": "燃やすで攻撃し、勝利した！" },
        "D": { "win": true, "message": "燃やすで攻撃し、勝利した！" },
        "E": { "win": true, "message": "燃やすで攻撃し、勝利した！" },
        "F": { "win": false, "message": "燃やすが効かず、敗北した..." },
        "G": { "win": true, "message": "燃やすで攻撃し、勝利した！" },
        "H": { "win": true, "message": "燃やすで攻撃し、勝利した！" },
        "I": { "win": false, "message": "燃やすが効かず、敗北した..." },
        "J": { "win": false, "message": "燃やすが効かず、敗北した..." },
        "K": { "win": true, "message": "燃やすで攻撃し、勝利した！" },
        "L": { "win": false, "message": "燃やすが効かず、敗北した..." },
        "M": { "win": true, "message": "燃やすで攻撃し、勝利した！" },
        "N": { "win": false, "message": "燃やすが効かず、敗北した..." },
        "O": { "win": false, "message": "燃やすが効かず、敗北した..." },
        "P": { "win": false, "message": "燃やすが効かず、敗北した..." },
        "Q": { "win": false, "message": "燃やすが効かず、敗北した..." },
        "R": { "win": false, "message": "燃やすが効かず、敗北した..." },
        "S": { "win": false, "message": "燃やすが効かず、敗北した..." },
        "T": { "win": false, "message": "燃やすが効かず、敗北した..." },
        "U": { "win": false, "message": "燃やすが効かず、敗北した..." },
        "V": { "win": false, "message": "燃やすが効かず、敗北した..." },
        "W": { "win": false, "message": "燃やすが効かず、敗北した..." },
        "X": { "win": false, "message": "燃やすが効かず、敗北した..." },
        "Y": { "win": false, "message": "燃やすが効かず、敗北した..." },
        "Z": { "win": false, "message": "燃やすが効かず、敗北した..." },
    },
    "凍らせる": {
        "A": { "win": false, "message": "凍らせるが効かず、敗北した..." },
        "B": { "win": true, "message": "凍らせるで攻撃し、勝利した！" },
        "C": { "win": true, "message": "凍らせるで攻撃し、勝利した！" },
        "D": { "win": true, "message": "凍らせるで攻撃し、勝利した！" },
        "E": { "win": true, "message": "凍らせるで攻撃し、勝利した！" },
        "F": { "win": true, "message": "凍らせるで攻撃し、勝利した！" },
        "G": { "win": true, "message": "凍らせるで攻撃し、勝利した！" },
        "H": { "win": true, "message": "凍らせるで攻撃し、勝利した！" },
        "I": { "win": true, "message": "凍らせるで攻撃し、勝利した！" },
        "J": { "win": false, "message": "凍らせるが効かず、敗北した..." },
        "K": { "win": false, "message": "凍らせるが効かず、敗北した..." },
        "L": { "win": false, "message": "凍らせるが効かず、敗北した..." },
        "M": { "win": true, "message": "凍らせるで攻撃し、勝利した！" },
        "N": { "win": false, "message": "凍らせるが効かず、敗北した..." },
        "O": { "win": true, "message": "凍らせるで攻撃し、勝利した！" },
        "P": { "win": false, "message": "凍らせるが効かず、敗北した..." },
        "Q": { "win": false, "message": "凍らせるが効かず、敗北した..." },
        "R": { "win": false, "message": "凍らせるが効かず、敗北した..." },
        "S": { "win": false, "message": "凍らせるが効かず、敗北した..." },
        "T": { "win": false, "message": "凍らせるが効かず、敗北した..." },
        "U": { "win": false, "message": "凍らせるが効かず、敗北した..." },
        "V": { "win": false, "message": "凍らせるが効かず、敗北した..." },
        "W": { "win": false, "message": "凍らせるが効かず、敗北した..." },
        "X": { "win": false, "message": "凍らせるが効かず、敗北した..." },
        "Y": { "win": true, "message": "凍らせるで攻撃し、勝利した！" },
        "Z": { "win": false, "message": "凍らせるが効かず、敗北した..." },
    },
    "罠": {
        "A": { "win": true, "message": "罠で攻撃し、勝利した！" },
        "B": { "win": true, "message": "罠で攻撃し、勝利した！" },
        "C": { "win": true, "message": "罠で攻撃し、勝利した！" },
        "D": { "win": true, "message": "罠で攻撃し、勝利した！" },
        "E": { "win": true, "message": "罠で攻撃し、勝利した！" },
        "F": { "win": true, "message": "罠で攻撃し、勝利した！" },
        "G": { "win": true, "message": "罠で攻撃し、勝利した！" },
        "H": { "win": true, "message": "罠で攻撃し、勝利した！" },
        "I": { "win": true, "message": "罠で攻撃し、勝利した！" },
        "J": { "win": true, "message": "罠で攻撃し、勝利した！" },
        "K": { "win": true, "message": "罠で攻撃し、勝利した！" },
        "L": { "win": false, "message": "罠が効かず、敗北した..." },
        "M": { "win": false, "message": "罠が効かず、敗北した..." },
        "N": { "win": true, "message": "罠で攻撃し、勝利した！" },
        "O": { "win": false, "message": "罠が効かず、敗北した..." },
        "P": { "win": false, "message": "罠が効かず、敗北した..." },
        "Q": { "win": false, "message": "罠が効かず、敗北した..." },
        "R": { "win": true, "message": "罠で攻撃し、勝利した！" },
        "S": { "win": false, "message": "罠が効かず、敗北した..." },
        "T": { "win": false, "message": "罠が効かず、敗北した..." },
        "U": { "win": false, "message": "罠が効かず、敗北した..." },
        "V": { "win": false, "message": "罠が効かず、敗北した..." },
        "W": { "win": false, "message": "罠が効かず、敗北した..." },
        "X": { "win": false, "message": "罠が効かず、敗北した..." },
        "Y": { "win": false, "message": "罠が効かず、敗北した..." },
        "Z": { "win": true, "message": "罠で攻撃し、勝利した！" },
    },
    "呪う": {
        "A": { "win": true, "message": "呪うで攻撃し、勝利した！" },
        "B": { "win": true, "message": "呪うで攻撃し、勝利した！" },
        "C": { "win": false, "message": "呪うが効かず、敗北した..." },
        "D": { "win": true, "message": "呪うで攻撃し、勝利した！" },
        "E": { "win": false, "message": "呪うが効かず、敗北した..." },
        "F": { "win": false, "message": "呪うが効かず、敗北した..." },
        "G": { "win": true, "message": "呪うで攻撃し、勝利した！" },
        "H": { "win": false, "message": "呪うが効かず、敗北した..." },
        "I": { "win": false, "message": "呪うが効かず、敗北した..." },
        "J": { "win": true, "message": "呪うで攻撃し、勝利した！" },
        "K": { "win": false, "message": "呪うが効かず、敗北した..." },
        "L": { "win": true, "message": "呪うで攻撃し、勝利した！" },
        "M": { "win": false, "message": "呪うが効かず、敗北した..." },
        "N": { "win": false, "message": "呪うが効かず、敗北した..." },
        "O": { "win": true, "message": "呪うで攻撃し、勝利した！" },
        "P": { "win": false, "message": "呪うが効かず、敗北した..." },
        "Q": { "win": false, "message": "呪うが効かず、敗北した..." },
        "R": { "win": true, "message": "呪うで攻撃し、勝利した！" },
        "S": { "win": false, "message": "呪うが効かず、敗北した..." },
        "T": { "win": false, "message": "呪うが効かず、敗北した..." },
        "U": { "win": false, "message": "呪うが効かず、敗北した..." },
        "V": { "win": false, "message": "呪うが効かず、敗北した..." },
        "W": { "win": false, "message": "呪うが効かず、敗北した..." },
        "X": { "win": false, "message": "呪うが効かず、敗北した..." },
        "Y": { "win": false, "message": "呪うが効かず、敗北した..." },
        "Z": { "win": false, "message": "呪うが効かず、敗北した..." },
    },
    "祈る": {
        "A": { "win": true, "message": "祈るで攻撃し、勝利した！" },
        "B": { "win": true, "message": "祈るで攻撃し、勝利した！" },
        "C": { "win": true, "message": "祈るで攻撃し、勝利した！" },
        "D": { "win": true, "message": "祈るで攻撃し、勝利した！" },
        "E": { "win": true, "message": "祈るで攻撃し、勝利した！" },
        "F": { "win": false, "message": "祈るが効かず、敗北した..." },
        "G": { "win": true, "message": "祈るで攻撃し、勝利した！" },
        "H": { "win": true, "message": "祈るで攻撃し、勝利した！" },
        "I": { "win": true, "message": "祈るで攻撃し、勝利した！" },
        "J": { "win": true, "message": "祈るで攻撃し、勝利した！" },
        "K": { "win": true, "message": "祈るで攻撃し、勝利した！" },
        "L": { "win": true, "message": "祈るで攻撃し、勝利した！" },
        "M": { "win": false, "message": "祈るが効かず、敗北した..." },
        "N": { "win": true, "message": "祈るで攻撃し、勝利した！" },
        "O": { "win": false, "message": "祈るが効かず、敗北した..." },
        "P": { "win": true, "message": "祈るで攻撃し、勝利した！" },
        "Q": { "win": false, "message": "祈るが効かず、敗北した..." },
        "R": { "win": false, "message": "祈るが効かず、敗北した..." },
        "S": { "win": false, "message": "祈るが効かず、敗北した..." },
        "T": { "win": true, "message": "祈るで攻撃し、勝利した！" },
        "U": { "win": false, "message": "祈るが効かず、敗北した..." },
        "V": { "win": false, "message": "祈るが効かず、敗北した..." },
        "W": { "win": false, "message": "祈るが効かず、敗北した..." },
        "X": { "win": false, "message": "祈るが効かず、敗北した..." },
        "Y": { "win": false, "message": "祈るが効かず、敗北した..." },
        "Z": { "win": false, "message": "祈るが効かず、敗北した..." },
    },
    "逃げる": {
        "A": { "win": true, "message": "逃げるで攻撃し、勝利した！" },
        "B": { "win": false, "message": "逃げるが効かず、敗北した..." },
        "C": { "win": true, "message": "逃げるで攻撃し、勝利した！" },
        "D": { "win": true, "message": "逃げるで攻撃し、勝利した！" },
        "E": { "win": true, "message": "逃げるで攻撃し、勝利した！" },
        "F": { "win": true, "message": "逃げるで攻撃し、勝利した！" },
        "G": { "win": false, "message": "逃げるが効かず、敗北した..." },
        "H": { "win": true, "message": "逃げるで攻撃し、勝利した！" },
        "I": { "win": true, "message": "逃げるで攻撃し、勝利した！" },
        "J": { "win": true, "message": "逃げるで攻撃し、勝利した！" },
        "K": { "win": true, "message": "逃げるで攻撃し、勝利した！" },
        "L": { "win": true, "message": "逃げるで攻撃し、勝利した！" },
        "M": { "win": false, "message": "逃げるが効かず、敗北した..." },
        "N": { "win": false, "message": "逃げるが効かず、敗北した..." },
        "O": { "win": true, "message": "逃げるで攻撃し、勝利した！" },
        "P": { "win": true, "message": "逃げるで攻撃し、勝利した！" },
        "Q": { "win": false, "message": "逃げるが効かず、敗北した..." },
        "R": { "win": false, "message": "逃げるが効かず、敗北した..." },
        "S": { "win": false, "message": "逃げるが効かず、敗北した..." },
        "T": { "win": false, "message": "逃げるが効かず、敗北した..." },
        "U": { "win": false, "message": "逃げるが効かず、敗北した..." },
        "V": { "win": false, "message": "逃げるが効かず、敗北した..." },
        "W": { "win": false, "message": "逃げるが効かず、敗北した..." },
        "X": { "win": false, "message": "逃げるが効かず、敗北した..." },
        "Y": { "win": false, "message": "逃げるが効かず、敗北した..." },
        "Z": { "win": true, "message": "逃げるで攻撃し、勝利した！" },
    },
    "説得": {
        "A": { "win": true, "message": "説得で攻撃し、勝利した！" },
        "B": { "win": false, "message": "説得が効かず、敗北した..." },
        "C": { "win": true, "message": "説得で攻撃し、勝利した！" },
        "D": { "win": true, "message": "説得で攻撃し、勝利した！" },
        "E": { "win": true, "message": "説得で攻撃し、勝利した！" },
        "F": { "win": true, "message": "説得で攻撃し、勝利した！" },
        "G": { "win": true, "message": "説得で攻撃し、勝利した！" },
        "H": { "win": true, "message": "説得で攻撃し、勝利した！" },
        "I": { "win": false, "message": "説得が効かず、敗北した..." },
        "J": { "win": false, "message": "説得が効かず、敗北した..." },
        "K": { "win": true, "message": "説得で攻撃し、勝利した！" },
        "L": { "win": true, "message": "説得で攻撃し、勝利した！" },
        "M": { "win": true, "message": "説得で攻撃し、勝利した！" },
        "N": { "win": true, "message": "説得で攻撃し、勝利した！" },
        "O": { "win": false, "message": "説得が効かず、敗北した..." },
        "P": { "win": true, "message": "説得で攻撃し、勝利した！" },
        "Q": { "win": false, "message": "説得が効かず、敗北した..." },
        "R": { "win": false, "message": "説得が効かず、敗北した..." },
        "S": { "win": true, "message": "説得で攻撃し、勝利した！" },
        "T": { "win": false, "message": "説得が効かず、敗北した..." },
        "U": { "win": false, "message": "説得が効かず、敗北した..." },
        "V": { "win": true, "message": "説得で攻撃し、勝利した！" },
        "W": { "win": true, "message": "説得で攻撃し、勝利した！" },
        "X": { "win": false, "message": "説得が効かず、敗北した..." },
        "Y": { "win": false, "message": "説得が効かず、敗北した..." },
        "Z": { "win": false, "message": "説得が効かず、敗北した..." },
    },
    "隠れる": {
        "A": { "win": true, "message": "隠れるで攻撃し、勝利した！" },
        "B": { "win": true, "message": "隠れるで攻撃し、勝利した！" },
        "C": { "win": true, "message": "隠れるで攻撃し、勝利した！" },
        "D": { "win": true, "message": "隠れるで攻撃し、勝利した！" },
        "E": { "win": true, "message": "隠れるで攻撃し、勝利した！" },
        "F": { "win": true, "message": "隠れるで攻撃し、勝利した！" },
        "G": { "win": true, "message": "隠れるで攻撃し、勝利した！" },
        "H": { "win": false, "message": "隠れるが効かず、敗北した..." },
        "I": { "win": true, "message": "隠れるで攻撃し、勝利した！" },
        "J": { "win": false, "message": "隠れるが効かず、敗北した..." },
        "K": { "win": false, "message": "隠れるが効かず、敗北した..." },
        "L": { "win": true, "message": "隠れるで攻撃し、勝利した！" },
        "M": { "win": false, "message": "隠れるが効かず、敗北した..." },
        "N": { "win": true, "message": "隠れるで攻撃し、勝利した！" },
        "O": { "win": false, "message": "隠れるが効かず、敗北した..." },
        "P": { "win": false, "message": "隠れるが効かず、敗北した..." },
        "Q": { "win": false, "message": "隠れるが効かず、敗北した..." },
        "R": { "win": false, "message": "隠れるが効かず、敗北した..." },
        "S": { "win": false, "message": "隠れるが効かず、敗北した..." },
        "T": { "win": true, "message": "隠れるで攻撃し、勝利した！" },
        "U": { "win": false, "message": "隠れるが効かず、敗北した..." },
        "V": { "win": false, "message": "隠れるが効かず、敗北した..." },
        "W": { "win": false, "message": "隠れるが効かず、敗北した..." },
        "X": { "win": false, "message": "隠れるが効かず、敗北した..." },
        "Y": { "win": false, "message": "隠れるが効かず、敗北した..." },
        "Z": { "win": false, "message": "隠れるが効かず、敗北した..." },
    },
    "騙す": {
        "A": { "win": true, "message": "騙すで攻撃し、勝利した！" },
        "B": { "win": true, "message": "騙すで攻撃し、勝利した！" },
        "C": { "win": true, "message": "騙すで攻撃し、勝利した！" },
        "D": { "win": true, "message": "騙すで攻撃し、勝利した！" },
        "E": { "win": true, "message": "騙すで攻撃し、勝利した！" },
        "F": { "win": false, "message": "騙すが効かず、敗北した..." },
        "G": { "win": true, "message": "騙すで攻撃し、勝利した！" },
        "H": { "win": false, "message": "騙すが効かず、敗北した..." },
        "I": { "win": true, "message": "騙すで攻撃し、勝利した！" },
        "J": { "win": true, "message": "騙すで攻撃し、勝利した！" },
        "K": { "win": false, "message": "騙すが効かず、敗北した..." },
        "L": { "win": false, "message": "騙すが効かず、敗北した..." },
        "M": { "win": false, "message": "騙すが効かず、敗北した..." },
        "N": { "win": true, "message": "騙すで攻撃し、勝利した！" },
        "O": { "win": true, "message": "騙すで攻撃し、勝利した！" },
        "P": { "win": false, "message": "騙すが効かず、敗北した..." },
        "Q": { "win": true, "message": "騙すで攻撃し、勝利した！" },
        "R": { "win": true, "message": "騙すで攻撃し、勝利した！" },
        "S": { "win": false, "message": "騙すが効かず、敗北した..." },
        "T": { "win": false, "message": "騙すが効かず、敗北した..." },
        "U": { "win": false, "message": "騙すが効かず、敗北した..." },
        "V": { "win": false, "message": "騙すが効かず、敗北した..." },
        "W": { "win": false, "message": "騙すが効かず、敗北した..." },
        "X": { "win": false, "message": "騙すが効かず、敗北した..." },
        "Y": { "win": false, "message": "騙すが効かず、敗北した..." },
        "Z": { "win": false, "message": "騙すが効かず、敗北した..." },
    },
    "威圧": {
        "A": { "win": true, "message": "威圧で攻撃し、勝利した！" },
        "B": { "win": true, "message": "威圧で攻撃し、勝利した！" },
        "C": { "win": true, "message": "威圧で攻撃し、勝利した！" },
        "D": { "win": true, "message": "威圧で攻撃し、勝利した！" },
        "E": { "win": true, "message": "威圧で攻撃し、勝利した！" },
        "F": { "win": true, "message": "威圧で攻撃し、勝利した！" },
        "G": { "win": true, "message": "威圧で攻撃し、勝利した！" },
        "H": { "win": false, "message": "威圧が効かず、敗北した..." },
        "I": { "win": false, "message": "威圧が効かず、敗北した..." },
        "J": { "win": true, "message": "威圧で攻撃し、勝利した！" },
        "K": { "win": false, "message": "威圧が効かず、敗北した..." },
        "L": { "win": false, "message": "威圧が効かず、敗北した..." },
        "M": { "win": true, "message": "威圧で攻撃し、勝利した！" },
        "N": { "win": true, "message": "威圧で攻撃し、勝利した！" },
        "O": { "win": true, "message": "威圧で攻撃し、勝利した！" },
        "P": { "win": false, "message": "威圧が効かず、敗北した..." },
        "Q": { "win": true, "message": "威圧で攻撃し、勝利した！" },
        "R": { "win": false, "message": "威圧が効かず、敗北した..." },
        "S": { "win": false, "message": "威圧が効かず、敗北した..." },
        "T": { "win": true, "message": "威圧で攻撃し、勝利した！" },
        "U": { "win": false, "message": "威圧が効かず、敗北した..." },
        "V": { "win": false, "message": "威圧が効かず、敗北した..." },
        "W": { "win": false, "message": "威圧が効かず、敗北した..." },
        "X": { "win": false, "message": "威圧が効かず、敗北した..." },
        "Y": { "win": false, "message": "威圧が効かず、敗北した..." },
        "Z": { "win": false, "message": "威圧が効かず、敗北した..." },
    },
    "媚びる": {
        "A": { "win": true, "message": "媚びるで攻撃し、勝利した！" },
        "B": { "win": true, "message": "媚びるで攻撃し、勝利した！" },
        "C": { "win": true, "message": "媚びるで攻撃し、勝利した！" },
        "D": { "win": true, "message": "媚びるで攻撃し、勝利した！" },
        "E": { "win": true, "message": "媚びるで攻撃し、勝利した！" },
        "F": { "win": true, "message": "媚びるで攻撃し、勝利した！" },
        "G": { "win": false, "message": "媚びるが効かず、敗北した..." },
        "H": { "win": false, "message": "媚びるが効かず、敗北した..." },
        "I": { "win": true, "message": "媚びるで攻撃し、勝利した！" },
        "J": { "win": false, "message": "媚びるが効かず、敗北した..." },
        "K": { "win": false, "message": "媚びるが効かず、敗北した..." },
        "L": { "win": false, "message": "媚びるが効かず、敗北した..." },
        "M": { "win": false, "message": "媚びるが効かず、敗北した..." },
        "N": { "win": false, "message": "媚びるが効かず、敗北した..." },
        "O": { "win": true, "message": "媚びるで攻撃し、勝利した！" },
        "P": { "win": false, "message": "媚びるが効かず、敗北した..." },
        "Q": { "win": false, "message": "媚びるが効かず、敗北した..." },
        "R": { "win": false, "message": "媚びるが効かず、敗北した..." },
        "S": { "win": true, "message": "媚びるで攻撃し、勝利した！" },
        "T": { "win": true, "message": "媚びるで攻撃し、勝利した！" },
        "U": { "win": false, "message": "媚びるが効かず、敗北した..." },
        "V": { "win": false, "message": "媚びるが効かず、敗北した..." },
        "W": { "win": false, "message": "媚びるが効かず、敗北した..." },
        "X": { "win": false, "message": "媚びるが効かず、敗北した..." },
        "Y": { "win": false, "message": "媚びるが効かず、敗北した..." },
        "Z": { "win": false, "message": "媚びるが効かず、敗北した..." },
    },
    "買収": {
        "A": { "win": true, "message": "買収で攻撃し、勝利した！" },
        "B": { "win": true, "message": "買収で攻撃し、勝利した！" },
        "C": { "win": true, "message": "買収で攻撃し、勝利した！" },
        "D": { "win": false, "message": "買収が効かず、敗北した..." },
        "E": { "win": true, "message": "買収で攻撃し、勝利した！" },
        "F": { "win": false, "message": "買収が効かず、敗北した..." },
        "G": { "win": false, "message": "買収が効かず、敗北した..." },
        "H": { "win": true, "message": "買収で攻撃し、勝利した！" },
        "I": { "win": true, "message": "買収で攻撃し、勝利した！" },
        "J": { "win": false, "message": "買収が効かず、敗北した..." },
        "K": { "win": true, "message": "買収で攻撃し、勝利した！" },
        "L": { "win": false, "message": "買収が効かず、敗北した..." },
        "M": { "win": true, "message": "買収で攻撃し、勝利した！" },
        "N": { "win": true, "message": "買収で攻撃し、勝利した！" },
        "O": { "win": false, "message": "買収が効かず、敗北した..." },
        "P": { "win": true, "message": "買収で攻撃し、勝利した！" },
        "Q": { "win": true, "message": "買収で攻撃し、勝利した！" },
        "R": { "win": false, "message": "買収が効かず、敗北した..." },
        "S": { "win": true, "message": "買収で攻撃し、勝利した！" },
        "T": { "win": false, "message": "買収が効かず、敗北した..." },
        "U": { "win": true, "message": "買収で攻撃し、勝利した！" },
        "V": { "win": false, "message": "買収が効かず、敗北した..." },
        "W": { "win": false, "message": "買収が効かず、敗北した..." },
        "X": { "win": false, "message": "買収が効かず、敗北した..." },
        "Y": { "win": false, "message": "買収が効かず、敗北した..." },
        "Z": { "win": false, "message": "買収が効かず、敗北した..." },
    },
    "毒": {
        "A": { "win": true, "message": "毒で攻撃し、勝利した！" },
        "B": { "win": true, "message": "毒で攻撃し、勝利した！" },
        "C": { "win": true, "message": "毒で攻撃し、勝利した！" },
        "D": { "win": false, "message": "毒が効かず、敗北した..." },
        "E": { "win": true, "message": "毒で攻撃し、勝利した！" },
        "F": { "win": false, "message": "毒が効かず、敗北した..." },
        "G": { "win": true, "message": "毒で攻撃し、勝利した！" },
        "H": { "win": true, "message": "毒で攻撃し、勝利した！" },
        "I": { "win": false, "message": "毒が効かず、敗北した..." },
        "J": { "win": true, "message": "毒で攻撃し、勝利した！" },
        "K": { "win": false, "message": "毒が効かず、敗北した..." },
        "L": { "win": false, "message": "毒が効かず、敗北した..." },
        "M": { "win": true, "message": "毒で攻撃し、勝利した！" },
        "N": { "win": true, "message": "毒で攻撃し、勝利した！" },
        "O": { "win": true, "message": "毒で攻撃し、勝利した！" },
        "P": { "win": false, "message": "毒が効かず、敗北した..." },
        "Q": { "win": false, "message": "毒が効かず、敗北した..." },
        "R": { "win": false, "message": "毒が効かず、敗北した..." },
        "S": { "win": true, "message": "毒で攻撃し、勝利した！" },
        "T": { "win": true, "message": "毒で攻撃し、勝利した！" },
        "U": { "win": false, "message": "毒が効かず、敗北した..." },
        "V": { "win": false, "message": "毒が効かず、敗北した..." },
        "W": { "win": false, "message": "毒が効かず、敗北した..." },
        "X": { "win": true, "message": "毒で攻撃し、勝利した！" },
        "Y": { "win": false, "message": "毒が効かず、敗北した..." },
        "Z": { "win": false, "message": "毒が効かず、敗北した..." },
    },
    "歌う": {
        "A": { "win": true, "message": "歌うで攻撃し、勝利した！" },
        "B": { "win": true, "message": "歌うで攻撃し、勝利した！" },
        "C": { "win": true, "message": "歌うで攻撃し、勝利した！" },
        "D": { "win": true, "message": "歌うで攻撃し、勝利した！" },
        "E": { "win": false, "message": "歌うが効かず、敗北した..." },
        "F": { "win": true, "message": "歌うで攻撃し、勝利した！" },
        "G": { "win": true, "message": "歌うで攻撃し、勝利した！" },
        "H": { "win": true, "message": "歌うで攻撃し、勝利した！" },
        "I": { "win": true, "message": "歌うで攻撃し、勝利した！" },
        "J": { "win": true, "message": "歌うで攻撃し、勝利した！" },
        "K": { "win": true, "message": "歌うで攻撃し、勝利した！" },
        "L": { "win": false, "message": "歌うが効かず、敗北した..." },
        "M": { "win": true, "message": "歌うで攻撃し、勝利した！" },
        "N": { "win": false, "message": "歌うが効かず、敗北した..." },
        "O": { "win": false, "message": "歌うが効かず、敗北した..." },
        "P": { "win": false, "message": "歌うが効かず、敗北した..." },
        "Q": { "win": true, "message": "歌うで攻撃し、勝利した！" },
        "R": { "win": false, "message": "歌うが効かず、敗北した..." },
        "S": { "win": false, "message": "歌うが効かず、敗北した..." },
        "T": { "win": false, "message": "歌うが効かず、敗北した..." },
        "U": { "win": false, "message": "歌うが効かず、敗北した..." },
        "V": { "win": false, "message": "歌うが効かず、敗北した..." },
        "W": { "win": true, "message": "歌うで攻撃し、勝利した！" },
        "X": { "win": false, "message": "歌うが効かず、敗北した..." },
        "Y": { "win": false, "message": "歌うが効かず、敗北した..." },
        "Z": { "win": false, "message": "歌うが効かず、敗北した..." },
    },
    "踊る": {
        "A": { "win": true, "message": "踊るで攻撃し、勝利した！" },
        "B": { "win": true, "message": "踊るで攻撃し、勝利した！" },
        "C": { "win": true, "message": "踊るで攻撃し、勝利した！" },
        "D": { "win": true, "message": "踊るで攻撃し、勝利した！" },
        "E": { "win": true, "message": "踊るで攻撃し、勝利した！" },
        "F": { "win": true, "message": "踊るで攻撃し、勝利した！" },
        "G": { "win": false, "message": "踊るが効かず、敗北した..." },
        "H": { "win": true, "message": "踊るで攻撃し、勝利した！" },
        "I": { "win": true, "message": "踊るで攻撃し、勝利した！" },
        "J": { "win": true, "message": "踊るで攻撃し、勝利した！" },
        "K": { "win": false, "message": "踊るが効かず、敗北した..." },
        "L": { "win": true, "message": "踊るで攻撃し、勝利した！" },
        "M": { "win": false, "message": "踊るが効かず、敗北した..." },
        "N": { "win": false, "message": "踊るが効かず、敗北した..." },
        "O": { "win": true, "message": "踊るで攻撃し、勝利した！" },
        "P": { "win": false, "message": "踊るが効かず、敗北した..." },
        "Q": { "win": false, "message": "踊るが効かず、敗北した..." },
        "R": { "win": true, "message": "踊るで攻撃し、勝利した！" },
        "S": { "win": false, "message": "踊るが効かず、敗北した..." },
        "T": { "win": true, "message": "踊るで攻撃し、勝利した！" },
        "U": { "win": false, "message": "踊るが効かず、敗北した..." },
        "V": { "win": false, "message": "踊るが効かず、敗北した..." },
        "W": { "win": false, "message": "踊るが効かず、敗北した..." },
        "X": { "win": true, "message": "踊るで攻撃し、勝利した！" },
        "Y": { "win": false, "message": "踊るが効かず、敗北した..." },
        "Z": { "win": false, "message": "踊るが効かず、敗北した..." },
    },
    "気合": {
        "A": { "win": true, "message": "気合で攻撃し、勝利した！" },
        "B": { "win": true, "message": "気合で攻撃し、勝利した！" },
        "C": { "win": true, "message": "気合で攻撃し、勝利した！" },
        "D": { "win": true, "message": "気合で攻撃し、勝利した！" },
        "E": { "win": true, "message": "気合で攻撃し、勝利した！" },
        "F": { "win": true, "message": "気合で攻撃し、勝利した！" },
        "G": { "win": true, "message": "気合で攻撃し、勝利した！" },
        "H": { "win": false, "message": "気合が効かず、敗北した..." },
        "I": { "win": false, "message": "気合が効かず、敗北した..." },
        "J": { "win": true, "message": "気合で攻撃し、勝利した！" },
        "K": { "win": true, "message": "気合で攻撃し、勝利した！" },
        "L": { "win": true, "message": "気合で攻撃し、勝利した！" },
        "M": { "win": true, "message": "気合で攻撃し、勝利した！" },
        "N": { "win": false, "message": "気合が効かず、敗北した..." },
        "O": { "win": true, "message": "気合で攻撃し、勝利した！" },
        "P": { "win": false, "message": "気合が効かず、敗北した..." },
        "Q": { "win": false, "message": "気合が効かず、敗北した..." },
        "R": { "win": true, "message": "気合で攻撃し、勝利した！" },
        "S": { "win": true, "message": "気合で攻撃し、勝利した！" },
        "T": { "win": false, "message": "気合が効かず、敗北した..." },
        "U": { "win": false, "message": "気合が効かず、敗北した..." },
        "V": { "win": false, "message": "気合が効かず、敗北した..." },
        "W": { "win": false, "message": "気合が効かず、敗北した..." },
        "X": { "win": false, "message": "気合が効かず、敗北した..." },
        "Y": { "win": false, "message": "気合が効かず、敗北した..." },
        "Z": { "win": false, "message": "気合が効かず、敗北した..." },
    },
}
